version: "3"
services:
  s1:
    image: fullpipe/jmock:latest
    volumes:
      - ./examples/mocks/s1:/mocks
    ports:
      - 9091:9090
  s2:
    image: fullpipe/jmock:latest
    volumes:
      - ./examples/mocks/s2:/mocks
    ports:
      - 9092:9090
  g:
    build: .
    volumes:
      - ./examples/methods:/methods
    environment:
      GASTON_JWT_HMACSECRET: qwertyuiopasdfghjklzxcvbnm123456
    ports:
      - 8080:8080
